### PR TITLE
Added example how register in symfony

### PR DESCRIPTION
**Pull request by mis4s**
Configuration symfony for the lazy one :)

### CODE REVIEW

**Comment by Finesse** [comment]
@Viperoo Thank you for the contribution! I am not expert in Symfony so I have a few questions:

1. Where should a user put the YML code you added? Could you please add a short answer to the readme.
2. Is adding your code all a user need to do to register the plugin in the Symfony's `Swift_Mailer` instance?
3. Can the plugin be improved to provide more convenient integration for Symfony?

There should be a «the» article before the «plugin» word in the «For Symfony you can register plugin this way» sentence, shouldn't it? I am not a native English speaker therefore I doubt.

**Comment by Finesse** [comment]
@Viperoo Hi! I need your response.

**Comment by mis4s** [comment]
1. In symfony, the developer decides where he wants to put the configuration. This can be the main file `config/services.yaml` or eg `config/packages/swiftmail.yaml`. The first line (`services`) is important for the developer.

2. Yes, because we are tagged in the container as a plugin to register in` Swift_Mailer` http://symfony.com/doc/current/reference/dic_tags.html#swiftmailer-default-plugin

3. No improves are needed because the class itself is well designed :)

Missing «the» have been added.

Thanks for your job.

**Comment by Finesse** [comment]
@Viperoo Merged. Thank you!

**Pull request merged**
